<?php

/**
 * @file
 * Contains helfi_proxy.
 */

use Drupal\Core\Asset\AttachedAssetsInterface;
use Drupal\editor\Entity\Editor;
use Drupal\helfi_proxy\ProxyManagerInterface;

/**
 * Converts uri to absolute.
 *
 * @param string $uri
 *   The uri to convert.
 *
 * @return string
 *   The absolute url.
 */
function helfi_proxy_absolute_url(string $uri) : string {
  static $relative_path = '';

  if (!$relative_path) {
    /** @var \Drupal\helfi_proxy\ProxyManagerInterface $service */
    $service = \Drupal::service('helfi_proxy.proxy_manager');
    $relative_path = $service
      ->getConfig(ProxyManagerInterface::ASSET_PATH);
  }
  /** @var \Drupal\Core\File\FileUrlGenerator $fileGenerator */
  $fileGenerator = \Drupal::service('file_url_generator');
  return '/' . $relative_path . $fileGenerator->transformRelative(
      $fileGenerator->generateAbsoluteString($uri)
    );
}

/**
 * Checks if proxy is configured.
 *
 * @return bool
 *   TRUE if proxy should be used.
 */
function helfi_proxy_is_configured() : bool {
  static $isConfigured = NULL;

  if ($isConfigured === NULL) {
    /** @var \Drupal\helfi_proxy\ProxyManagerInterface $service */
    $service = \Drupal::service('helfi_proxy.proxy_manager');
    $isConfigured = $service->isConfigured(ProxyManagerInterface::ASSET_PATH);
  }
  return $isConfigured;
}

/**
 * Implements hook_js_settings_alter().
 */
function helfi_proxy_js_settings_alter(
  array &$settings,
  AttachedAssetsInterface $assets
) {
  if (!helfi_proxy_is_configured()) {
    return;
  }
  foreach (['designSelect', 'paragraphSelect'] as $type) {
    if (!isset($settings[$type]['pathToImages'])) {
      continue;
    }
    $settings[$type]['pathToImages'] = helfi_proxy_absolute_url($settings[$type]['pathToImages']);
  }

  foreach (['hdbtSubthemeIconsPath', 'iconsPath'] as $key) {
    if (!isset($settings[$key])) {
      continue;
    }
    $settings[$key] = helfi_proxy_absolute_url($settings[$key]);
  }
}

/**
 * Implements hook_editor_js_settings_alter().
 */
function helfi_proxy_editor_js_settings_alter(array &$settings) {
  if (!\Drupal::moduleHandler()->moduleExists('ckeditor') || !helfi_proxy_is_configured()) {
    return;
  }
  $ckeditor_plugin_manager = \Drupal::service('plugin.manager.ckeditor.plugin');

  foreach ($settings['editor']['formats'] as $format => &$format_settings) {
    if ($format_settings['editor'] === 'ckeditor') {
      $editor = Editor::load($format);
      // @see \Drupal\ckeditor\Plugin\Editor\CKEditor::getJSSettings()
      $external_plugin_files = $ckeditor_plugin_manager->getEnabledPluginFiles($editor);
      // Convert editor css and plugin js to use absolute path.
      $format_settings['editorSettings']['drupalExternalPlugins'] = array_map('helfi_proxy_absolute_url', $external_plugin_files);
      $format_settings['editorSettings']['contentsCss'] = array_map('helfi_proxy_absolute_url', $format_settings['editorSettings']['contentsCss'] ?? []);
    }
  }

}
