helfi_proxy.settings:
  type: config_entity
  mapping:
    tunnistamo_return_url:
      type: string
    instance_name:
      type: string
    prefixes:
      type: sequence
      sequence:
        type: string

