on:
  pull_request:
  push:
    branches:
      - main
name: CI
jobs:
  tests:
    strategy:
      matrix:
        php-versions: ['8.3']
    uses: city-of-helsinki/drupal-gh-actions/.github/workflows/module-tests.yml@main
    with:
      php_version: ${{ matrix.php-versions }}
      composer_dev_dependencies: 'drupal/redirect drupal/helfi_tunnistamo drupal/simple_sitemap drupal/varnish_purger'
    secrets:
      sonarcloud_token: ${{ secrets.SONAR_TOKEN }}
